version: '2'
services:
  app:
    image: game-of-life:latest
    container_name: app
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - gol
    volumes:
      - "./frontend/dist:/frontend/"
      - "./resources:/resources/"
networks:
  gol:
    driver: bridge