version: '2'
services:
  app:
    image: game-of-life:latest
    container_name: app
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - gol
    volumes:
      - "./frontend/dist:/frontend/"
      - "./resources:/resources/"
  mongodb:
    image: mongo:3.6.0
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    networks:
      - gol
    command: mongod --smallfiles --logpath=/dev/null
networks:
  gol:
    driver: bridge